add circleci validationas well

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -49,6 +49,15 @@ workflows:
 
 version: 2
 jobs:
+  validate-config:
+    steps:
+      - run:
+        - >
+          if ! eMSG=$(circleci config validate -c .circleci/config.yml); then
+            echo "CircleCI Configuration Failed Validation."
+            echo $eMSG
+            exit 1
+          fi
   node-base-test: &node-base-test
     working_directory: ~/analytics-node
     docker:
